sudo: required
language: c
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gfortran-7
          - gcc-7
      env:
        - BUILD_TARGET=mpi_gnu_linux_64

    - os: osx
      osx_image: xcode9.2
      env:
        - BUILD_TARGET=mpi_gnu_osx_64

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then ./install-ompi.sh && export LD_LIBRARY_PATH=/opt/openmpi-3.0.2/lib:$LD_LIBRARY_PATH && export PATH=/opt/openmpi-3.0.2/bin:$PATH; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install open-mpi; fi
before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then export LD_LIBRARY_PATH=/opt/openmpi-3.0.2/lib:$LD_LIBRARY_PATH && export PATH=/opt/openmpi-3.0.2/bin:$PATH; fi
script:
    - cd Build/${BUILD_TARGET}
    - ./make_fds.sh        
